Improvement: Added Elementor v3.1 compatibility
brainstormforce/header-footer-elementor pull request #351
Opened 2021-03-04 06:53 UTC by sushmak02

### Description
_register_controls method deprecated with Elementor v3.1. Added compatibility to this.
Updated the Stable and tested up to tags.

### Screenshots

### Types of changes

Imporovement (non-breaking change which adds functionality) 

### How has this been tested?
Drag-drop all the widgets on the page. Make sure the widgets work properly.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-04 07:22 UTC, vrundakansara requested changes

2021-03-04 07:22 UTC, vrundakansara commented on inc/widgets-manager/widgets/class-cart.php
> +	protected function register_controls() {
@sushmak02 - Will this make sure that the users using older Elementor (< v3.1) will not face any issues?

2021-03-05 11:21 UTC, sushmak02 commented on inc/widgets-manager/widgets/class-cart.php
> +	protected function register_controls() {
We will keep the deprecated function `_register_controls` too.

2021-03-05 11:29 UTC, vrundakansara approved these changes

2021-03-08 07:52 UTC, merged