New: Email integration on the settings page with About Us changes
brainstormforce/header-footer-elementor pull request #378
Opened 2021-06-07 05:51 UTC by sushmak02

### Description

Added new sections on the settings pages for HFE. This includes Email Integration, Addons information, and about us sections.

Refer to this Doc for the plan - https://docs.google.com/document/d/1d1G8JaXcrGG6o_KctAwszGZypmjMXA9p3f511J-9PdE/edit?ts=601be28a#heading=h.fnkogv3gmbop

Here is a task for the same - https://trello.com/c/IpxtwVaB/90-email-integration-task

### Screenshots
All Templates -> Click on Add New Button -> https://share.getcloudapp.com/L1uNqG7E
Step-By-Step Guide Page -> https://share.getcloudapp.com/nOulGznr
About Us Page -> https://share.getcloudapp.com/P8ukL0mg
Footer Notice -> https://share.getcloudapp.com/E0u9x2yp
Plugin Activation Notice -> https://share.getcloudapp.com/X6u9mknk

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
Test the Modal Popup working. ( The popup should display only once to a user )
Subscribe Form
Responsiveness
Plugin activation notice should display only on the plugins page
Footer message should display on HFE pages only

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-06-07 08:31 UTC, sushmak02 commented on admin/class-addons-actions.php
> +	return apply_filters( 'hfe_api_domain', 'https://mitras11.sg-host.com/' );
Once Astra-sites-server PR gets merged, this URL needs to get updated with websitedemos site URL.

2021-06-07 10:35 UTC, vrundakansara requested changes

2021-06-07 10:35 UTC, vrundakansara commented on inc/class-header-footer-elementor.php
> +	public function setup_unsupported_theme( $hfe_settings_tabs ) {
Have you checked this with backward compatibility? Will adding function parameter call for some errors?

2021-06-07 10:35 UTC, vrundakansara commented on admin/class-addons-actions.php
> +<?php
Any reason why namespace is not used here and also no class is defined?

2021-06-07 10:35 UTC, vrundakansara commented on admin/assets/js/ehf-admin.js
> +		_animate_fields: function ( event ) {
Use consistency in function names.

2021-06-07 14:26 UTC, sushmak02 commented on admin/assets/js/ehf-admin.js
> +		_animate_fields: function ( event ) {
Done!

2021-06-07 14:32 UTC, sushmak02 commented on inc/class-header-footer-elementor.php
> +	public function setup_unsupported_theme( $hfe_settings_tabs ) {
Yes, I have checked this with backward compatibility. This will not cause any errors!

2021-06-07 14:34 UTC, sushmak02 commented on admin/class-addons-actions.php
> +<?php
We are using WordPress classes here. After using namespaces, it gives errors while accessing classes.
I have added class here with ABSPATH condition check.

2021-06-14 08:53 UTC, vrundakansara requested changes

2021-06-14 08:53 UTC, vrundakansara commented on admin/assets/js/ehf-admin.js
> +					'install': 'hfe_install_addon',
Use wp.updates library to install and activate plugins and theme, instead of using AJAX function.
```php
wp.updates.installTheme({
	slug: theme_slug
});
```

2021-06-15 14:52 UTC, sushmak02 commented on admin/assets/js/ehf-admin.js
> +					'install': 'hfe_install_addon',
Added similar function for Theme and Plugin installation. Please check

2021-06-17 04:24 UTC, vrundakansara requested changes

2021-06-17 04:24 UTC, vrundakansara commented on header-footer-elementor.php
> +define( 'HFE_VER', '1.5.10' );
Do update the version in the top comment section. [Ref](https://github.com/brainstormforce/header-footer-elementor/pull/378/files#diff-82ee260aaf0c8764e241ccad11db6b10d7ba6d58fdcbf940b9c402f45dff2407R10)

2021-06-17 04:24 UTC, vrundakansara commented on header-footer-elementor.php
> +	add_option( 'HFE_Plugin_Activated', 'yes' );
Let's use update_option here and rename the option name to `hfe_plugin_activated`.

2021-06-17 04:32 UTC, sushmak02 commented on header-footer-elementor.php
> +	add_option( 'HFE_Plugin_Activated', 'yes' );
Done!

2021-06-17 04:33 UTC, sushmak02 commented on header-footer-elementor.php
> +define( 'HFE_VER', '1.5.10' );
Done!

2021-06-17 09:56 UTC, vrundakansara approved these changes

2021-06-17 09:56 UTC, merged