Chore: v1.5.10
brainstormforce/header-footer-elementor pull request #381
Opened 2021-06-17 10:35 UTC by sushmak02

### Description
- New: Added Email Subscription and About Us section on the settings page.
- New: Rename plugin to be Elementor Header & Footer Builder.
- Improvement: Added an option to hide + & - sign added by Twenty Twenty-One Theme.
- Fix: Navigation Menu - Top distance option for dropdown adding a top margin to sub-menu.
- Fix: Navigation Menu - Fixed active color issues in case of full-page anchor links used in nav links.
- Fix: Navigation Menu - Navigation schema not working.

### Screenshots
https://share.getcloudapp.com/L1uNqG7E

### Types of changes

New feature (non-breaking change which adds functionality) 
Fixes & Improvements

### How has this been tested?
- Test Email Integration functionality in popup
- Test Addons feature on About Us settings page
- Test all the Navigation menu fixes

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-06-21 09:36 UTC, sushmak02 commented on inc/widgets-manager/widgets/class-navigation-menu.php
> +						 	{{WRAPPER}} .hfe-flyout-wrapper .hfe-flyout-container .hfe-nav-menu ul.sub-menu',
@swapnilde Confirm this change!

2021-06-21 13:50 UTC, vrundakansara requested changes

2021-06-21 13:50 UTC, vrundakansara commented on inc/js/frontend.js
> +					if (linkValue.length > 0) {
This will throw console error when linkValue is not set i.e when # value is not set.

2021-06-21 13:50 UTC, vrundakansara commented on header-footer-elementor.php
> +	update_option( 'HFE_Plugin_Activated', 'yes' );
Please rename the option name to `hfe_plugin_activated`.

2021-06-21 14:27 UTC, swapnilde commented on inc/js/frontend.js
> +					if (linkValue.length > 0) {
Fixed.

2021-06-21 15:02 UTC, sushmak02 commented on header-footer-elementor.php
> +	update_option( 'HFE_Plugin_Activated', 'yes' );
Done!

2021-06-21 15:34 UTC, sushmak02 commented
@vrundakansara Done with suggested changes!

2021-06-21 16:20 UTC, swapnilde commented
Found plugin old name:
File: class-header-footer-elementor.php
Line no.: 280
SS: https://share.getcloudapp.com/BluKK8xG

2021-06-21 16:27 UTC, sushmak02 commented
@swapnilde Done! Please check

2021-06-21 16:35 UTC, swapnilde approved these changes
Looks all good.

2021-06-22 07:13 UTC, vrundakansara approved these changes

2021-06-22 07:26 UTC, merged