Aria-label rule accessibility for navigation bar
brainstormforce/header-footer-elementor pull request #664
Opened 2023-04-07 12:24 UTC by vijetaR

### Description
Fixed accessibility error logs for navigation bar.

### Screenshots
https://i.imgur.com/XVYjHjM.png
### Types of changes

 Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?
- Drag/Drop navigation menu in a section/container
- Check on mobile menu for lighthouse accessibility

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-11 08:18 UTC, mahajanleena1995 requested changes

2023-04-11 08:18 UTC, mahajanleena1995 commented on inc/js/frontend.js
> +		if ( window.matchMedia( "( max-width: 1024px )" ).matches && $( '.elementor-element-' + id ).hasClass('hfe-nav-menu__breakpoint-mobile') ) {
@vijetaR Shouldn't this breakpoint be different for mobile (767px)?

2023-05-05 09:09 UTC, mahajanleena1995 approved these changes

2023-05-08 07:14 UTC, sushmak02 approved these changes

2023-05-10 05:55 UTC, merged