Build: Release PR Release candidate to Master PR for version 1.6.14
brainstormforce/header-footer-elementor pull request #671
Opened 2023-05-10 07:46 UTC by mahajanleena1995

### Description
- Final release PR. Please check all the checklist below before merging.
---
### Checklist:
- [x] Check if astra-notice library is updated to latest
- [x] Check if Elementor & Elementor Pro compatibility tags are updated to latest
- [x] Update - Tested Upto - readme.txt
- [x] Update Readme.txt file and then run: `grunt readme`
- [x] Run to update version number  : `grunt version-bump --ver=<version-number>`
- [x] Generate POT file             : `grunt i18n`
- [x] PHPCS - vendor/bin/phpcs
- [x] Add draft a tag GitHub
- [x] Open PR to backport branch to `next-release`
---

### Description
Changelog - 
- Improvement: Compatibility with Elementor version 3.13 and Elementor Pro version 3.13
- Fix: Navigation Menu - Accessibility error corrected for [aria-hidden="true"] attribute.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-05-10 10:24 UTC, vrundakansara approved these changes

2023-05-10 12:36 UTC, sushmak02 approved these changes

2023-05-11 04:12 UTC, patilvikasj commented on inc/js/frontend.js
> +		}
@mahajanleena1995 We can combine these 2 if conditions. I guess the only difference is of max-width value.

2023-05-11 04:12 UTC, patilvikasj requested changes
Please check comment

2023-05-11 04:17 UTC, mahajanleena1995 commented on inc/js/frontend.js
> +		}
@patilvikasj `hasClass` condition also have different values, should I still combine both using OR

2023-05-11 04:31 UTC, patilvikasj commented on inc/js/frontend.js
> +		}
Got it. No need to combine them.

2023-05-11 04:32 UTC, patilvikasj commented on inc/widgets-manager/widgets/class-navigation-menu.php
> +					<span class="screen-reader-text">Menu</span>
This `Menu` string needs to be translatable.

2023-05-11 04:44 UTC, mahajanleena1995 commented on inc/widgets-manager/widgets/class-navigation-menu.php
> +					<span class="screen-reader-text">Menu</span>
Updated here - https://github.com/brainstormforce/header-footer-elementor/pull/673

2023-05-11 04:51 UTC, RajkiranBagal approved these changes

2023-05-11 08:58 UTC, patilvikasj approved these changes

2023-05-11 09:54 UTC, merged