VIP Go rules for Header Footer Elementor
brainstormforce/header-footer-elementor pull request #715
Opened 2023-08-09 07:08 UTC by vijetaR

### Description
VIP Go rules set

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-10-26 10:18 UTC, mahajanleena1995 requested changes

2023-10-26 10:18 UTC, mahajanleena1995 commented on admin/class-hfe-addons-actions.php
>  			$arguments = isset( $_POST['data'] ) ? array_map( 'sanitize_text_field', json_decode( stripslashes( $_POST['data'] ), true ) ) : [];
@vijetaR the $_POST['data'] variable seems sanitized, so why the PHPCS ignore comment is added here?

2023-10-26 10:18 UTC, mahajanleena1995 commented on admin/class-hfe-admin.php
>  		if ( ! isset( $_POST['ehf_meta_nounce'] ) || ! wp_verify_nonce( $_POST['ehf_meta_nounce'], 'ehf_meta_nounce' ) ) {
@vijetaR Use sanitize_text_field here and remove PHPCS ignore comment

2023-10-26 10:18 UTC, mahajanleena1995 commented on admin/class-hfe-admin.php
> +			update_post_meta( $post_id, 'ehf_template_type', esc_attr( $_POST['ehf_template_type'] ) ); // PHPCS:Ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
@vijetaR Use sanitize_text_field here and remove PHPCS ignore comment

2023-10-26 10:18 UTC, mahajanleena1995 commented on admin/class-hfe-admin.php
> +			update_post_meta( $post_id, 'display-on-canvas-template', esc_attr( $_POST['display-on-canvas-template'] ) ); // PHPCS:Ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
@vijetaR Use sanitize_text_field here and remove PHPCS ignore comment

2023-10-26 10:18 UTC, mahajanleena1995 commented on inc/widgets-manager/widgets/class-retina.php
> +			if ( isset( $_SERVER['HTTP_USER_AGENT'] ) && strpos( $_SERVER['HTTP_USER_AGENT'], 'Chrome' ) !== false ) {
@vijetaR Use sanitize_text_field here and remove PHPCS ignore comment for WordPress.Security.ValidatedSanitizedInput.InputNotSanitized

2023-10-26 10:18 UTC, mahajanleena1995 commented on inc/widgets-manager/widgets/class-page-title.php
> +					<a {{{ view.getRenderAttributeString( 'url' ) }}} > <?php // PHPCS:Ignore WordPressVIPMinimum.Security.Mustache.OutputNotation ?>
@vijetaR this PHPCS error can be fixed like this - https://github.com/brainstormforce/ultimate-elementor/pull/482/files#diff-5f5202b5bd876829e5eaf06aa724e1c46ea840ca804360b0f9638c78bc8c2266R634

However, make sure to test this in the editor and on the front end in the HTML markup. It might not work properly in editor for icons.

2023-10-26 12:02 UTC, vijetaR commented on admin/class-hfe-addons-actions.php
>  			$arguments = isset( $_POST['data'] ) ? array_map( 'sanitize_text_field', json_decode( stripslashes( $_POST['data'] ), true ) ) : [];
@mahajanleena1995 I have added,  PHPCS analysis has detected and suggested fixing this warning even though the code **$_POST['data']** is correctly sanitizing and validating the input.

2023-10-26 13:03 UTC, vijetaR commented on inc/widgets-manager/widgets/class-page-title.php
> +					<a {{{ view.getRenderAttributeString( 'url' ) }}} > <?php // PHPCS:Ignore WordPressVIPMinimum.Security.Mustache.OutputNotation ?>
@mahajanleena1995 On change, the issue is that the output is displaying as HTML tags, and this is causing problems in both the page editor and the front end of the website.

2023-10-27 09:21 UTC, mahajanleena1995 approved these changes

2023-10-30 04:33 UTC, sushmak02 approved these changes

2023-10-30 04:33 UTC, merged