EPS-486: Sanitisation of code reported
brainstormforce/header-footer-elementor pull request #786
Opened 2024-03-27 10:10 UTC by vijetaR

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2024-03-27 13:45 UTC, vrundakansara requested changes

2024-03-27 13:45 UTC, vrundakansara commented on admin/class-hfe-admin.php
> +			esc_url( HFE_URL ) . 'assets/css/style.css',
Do you think we need to escape the URL that we are registering for WP?

2024-03-27 13:45 UTC, vrundakansara commented on admin/class-hfe-admin.php
> +			esc_attr( HFE_VER )
This will always be a version, we do not need to escape this

2024-04-01 17:28 UTC, vijetaR commented on admin/class-hfe-admin.php
> +			esc_url( HFE_URL ) . 'assets/css/style.css',
No, In this case, the `HFE_URL` constant isn't at risk of XSS attacks because it's set using `plugins_url()` and `__FILE__`, which are fixed values determined by the server, not influenced by user input.

2024-04-02 04:33 UTC, sushmak02 approved these changes
Update changelog

2024-04-02 04:54 UTC, vijetaR commented
@sushmak02 Its a continuation of the below PR
https://github.com/brainstormforce/header-footer-elementor/pull/783
https://github.com/brainstormforce/header-footer-elementor/pull/784
I have added changelog PR in 784

2024-04-03 04:15 UTC, vrundakansara approved these changes

2024-04-03 04:15 UTC, vrundakansara commented
@vijetaR - Can you fix the lint?

2024-04-03 07:19 UTC, vijetaR commented
Will try to fix and check if resolving.

2024-04-05 09:04 UTC, merged