Phpstan issue fixes
brainstormforce/header-footer-elementor pull request #848
Opened 2024-07-02 10:03 UTC by akshayurankar48

### Description
Fixed PHPStan issues for HFE

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2024-07-09 12:22 UTC, vijetaR approved these changes

2024-07-16 12:47 UTC, sushmak02 commented on inc/widgets-manager/widgets/class-search-button.php
> +	protected function register_controls(): void {
Remove : void if not needful

2024-07-18 06:16 UTC, sarangshahane commented on inc/lib/astra-notices/class-astra-notices.php
@akshayurankar48  Ideally, we should avoid doing PHPCS, PHPStan for Library files. Here in this case, skip the Astra notices library. 

The PHStan and PHPCS has to be done from the Astra Notices library only not from this HFE plugin.

2024-07-18 06:17 UTC, sarangshahane commented on inc/lib/target-rule/class-astra-target-rules-fields.php
Same for this file too.

2024-07-18 06:21 UTC, sarangshahane commented on inc/class-hfe-settings-page.php
>  					esc_html( "This method hides your theme's header & footer template with CSS and displays custom templates from the plugin.", 'header-footer-elementor' ),
These strings are not translation ready.

2024-07-18 06:21 UTC, sarangshahane commented on inc/class-hfe-settings-page.php
>  				wp_kses( 'Sometimes above methods might not work well with your theme, in this case, contact your theme author and request them to add support for the <a href="https://github.com/Nikschavan/heade
This string is not translation ready.

2024-07-18 06:52 UTC, sarangshahane commented on inc/widgets-manager/widgets/class-retina.php
> +				'placeholder' => __( 'https://your-link.com', 'header-footer-elementor' ),
I don't this this placeholder needs to be translated. This is an example of the URL. Instead here we can just keep the placeholder as `https://`

2024-07-18 06:54 UTC, sarangshahane commented on inc/widgets-manager/widgets/class-retina.php
> +				'size_units' => [ 'px', 'em', '%' ],
As you have changed the writing syntax for array from `[]` to `array()` Make that change here as well. 
Ex: array( 'px', 'em', '%' )

2024-07-18 07:20 UTC, sarangshahane commented on readme.txt
> +- Improvement: - Added support for PHPStan for improved code quality checks.
```suggestion
- Improvement: - Improved code quality syntax and secutiry checks for better coding standerds and practices.
```
@akshayurankar48 / @sushmak02 You can surely modify the changelog if required.

2024-07-18 07:22 UTC, sarangshahane commented on themes/bb-theme/class-hfe-bb-theme-compat.php
> +	 * // phpcs:ignore
Add a one liner reason for why this code is been ignored.

Example: Reason: your sentance.

2024-07-18 07:22 UTC, sarangshahane commented on themes/bb-theme/class-hfe-bb-theme-compat.php
> +	// phpcs:ignore
Same here.

2024-07-18 07:30 UTC, sarangshahane commented on themes/bb-theme/class-hfe-bb-theme-compat.php
> +	 * // phpcs:ignore
Create separate template for all HTML and avoid writing the ignore lines. 

Add the templates/views/html folders to the PHPStan config for ignore.

2024-07-18 07:31 UTC, sarangshahane commented on themes/oceanwp/class-hfe-oceanwp-compat.php
> +	// phpcs:ignore
Why this ignore lines here? If not required then remove it.

2024-07-18 07:32 UTC, sarangshahane commented on themes/storefront/class-hfe-storefront-compat.php
> +	 * @var ?HFE_Storefront_Compat
Spell mistake use `$` instead of `?`
```suggestion
	 * @var $HFE_Storefront_Compat
```

2024-07-18 07:33 UTC, sarangshahane commented on README.md
> +- Improvement: - Added support for PHPStan for improved code quality checks.
```suggestion
- Improvement: - Improved code quality syntax and secutiry checks for better coding standerds and practices.
```

2024-07-18 07:34 UTC, sarangshahane requested changes
@akshayurankar48 / @sushmak02 Please check the comments added on the PR they are minor but needs to be done before release.

2024-07-19 05:56 UTC, akshayurankar48 commented on inc/lib/astra-notices/class-astra-notices.php
Got it @sarangshahane reverted both the files

2024-07-19 05:56 UTC, akshayurankar48 commented on inc/lib/target-rule/class-astra-target-rules-fields.php
updated @sarangshahane

2024-07-19 05:59 UTC, akshayurankar48 commented on inc/class-hfe-settings-page.php
>  				wp_kses( 'Sometimes above methods might not work well with your theme, in this case, contact your theme author and request them to add support for the <a href="https://github.com/Nikschavan/heade
@sarangshahane does this seem okay - https://bsf.d.pr/i/pc04XN

2024-07-19 06:06 UTC, akshayurankar48 commented on readme.txt
> +- Improvement: - Added support for PHPStan for improved code quality checks.
Done @sarangshahane

2024-07-19 06:09 UTC, akshayurankar48 commented on README.md
> +- Improvement: - Added support for PHPStan for improved code quality checks.
Done @sarangshahane

2024-07-19 06:11 UTC, akshayurankar48 commented on themes/storefront/class-hfe-storefront-compat.php
> +	 * @var ?HFE_Storefront_Compat
This is updated @sarangshahane

2024-07-19 06:15 UTC, akshayurankar48 commented on themes/oceanwp/class-hfe-oceanwp-compat.php
> +	// phpcs:ignore
done @sarangshahane

2024-07-19 06:18 UTC, akshayurankar48 commented on inc/widgets-manager/widgets/class-retina.php
> +				'placeholder' => __( 'https://your-link.com', 'header-footer-elementor' ),
updated  @sarangshahane

2024-07-23 05:51 UTC, vijetaR commented on README.md
> +- Improvement: - Improved code quality syntax and secutiry checks for better coding standerds and practices.
Security spelling

2024-07-26 05:04 UTC, sushmak02 commented on inc/widgets-manager/widgets/class-retina.php
> +				'placeholder' => __( 'https://', 'header-footer-elementor' ),
why this change?

2024-07-26 05:04 UTC, sushmak02 approved these changes

2024-08-15 07:56 UTC, sushmak02 commented on inc/widgets-manager/widgets/class-retina.php
> +				'placeholder' => __( 'https://', 'header-footer-elementor' ),
@akshayurankar48 👆

2024-08-20 03:33 UTC, akshayurankar48 commented on inc/widgets-manager/widgets/class-retina.php
> +				'placeholder' => __( 'https://', 'header-footer-elementor' ),
reverted the change

2024-08-20 05:11 UTC, sushmak02 approved these changes

2024-08-20 05:13 UTC, merged