SVG
brainstormforce/header-footer-elementor pull request #920
Opened 2024-10-28 11:18 UTC by vijetaR

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2024-10-29 04:19 UTC, sushmak02 commented on inc/widgets-manager/class-widgets-loader.php
> +			$svg_handler = Plugin::instance()->assets_manager->get_asset( 'svg' );
earlier it was get_asset( 'svg-handler' ); right?

2024-10-29 05:44 UTC, vijetaR commented on inc/widgets-manager/class-widgets-loader.php
> +			$svg_handler = Plugin::instance()->assets_manager->get_asset( 'svg' );
Updated it, svg-handler @sushmak02 
```
[29-Oct-2024 04:46:21 UTC] Elementor\Core\Files\Assets\Manager Object
(
    [asset_types:protected] => Array
        (
            [svg-handler] => Elementor\Core\Files\Assets\Svg\Svg_Handler Object
                (
                    [attachment_id:Elementor\Core\Files\Assets\Svg\Svg_Handler:private] =>
                )
        )
)
```

2024-10-29 07:38 UTC, sushmak02 approved these changes

2024-10-30 11:10 UTC, kudaleganesh approved these changes

2024-11-01 17:12 UTC, vijetaR commented on readme.txt
> +- Fix: This update addressed a security bug. Props to Francesco Carlucci for privately reporting it to our team. Please make sure you are using the latest version on your website.
Updated the above feedback

2024-11-05 08:54 UTC, vrundakansara requested changes

2024-11-05 09:24 UTC, vijetaR commented on inc/class-hfe-settings-page.php
> +			$libxml_disable_entity_loader = libxml_disable_entity_loader( true );
@vrundakansara I have disabled phpcs in certain places to temporarily bypass specific coding standard checks that might not apply or cause any error in that context.

2024-11-05 09:50 UTC, vrundakansara commented on inc/class-hfe-settings-page.php
> +			$libxml_disable_entity_loader = libxml_disable_entity_loader( true );
Please put up the reasons in comments for all the ignore cases.

2024-11-05 10:14 UTC, vijetaR commented on inc/class-hfe-settings-page.php
> +			$libxml_disable_entity_loader = libxml_disable_entity_loader( true );
Updated

2024-11-05 13:11 UTC, vrundakansara requested changes

2024-11-05 13:11 UTC, vrundakansara commented on inc/class-hfe-settings-page.php
> +		// phpcs:enable WordPress.PHP.YodaConditions.NotYoda
```suggestion
		if ( $is_encoded ) {
			$original_content = gzdecode( $original_content );
			if ( false === $original_content ) {
				return '';
			}
		}
```

2024-11-05 13:11 UTC, vrundakansara commented on inc/class-hfe-settings-page.php
> +			if ( ! in_array( strtolower( $current_element->tagName ), $allowed_tags ) ) {
```suggestion
			if ( ! in_array( strtolower( $current_element->tagName ), $allowed_tags, true ) ) {
```

2024-11-05 13:11 UTC, vrundakansara commented on inc/class-hfe-settings-page.php
> +		// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase, WordPress.PHP.StrictInArray
```suggestion
		// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
```

2024-11-05 13:11 UTC, vrundakansara commented on inc/class-hfe-settings-page.php
> +			// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
Since this snakecase is ignored in many places, you can ignore it in entire project by mentioning in the phpcs.xml file exclude rules - UsedPropertyNotSnakeCase

2024-11-05 13:11 UTC, vrundakansara commented on inc/class-hfe-settings-page.php
> +			// phpcs:enable Generic.PHP.DeprecatedFunctions.Deprecated, WordPress.PHP.StrictInArray
```suggestion
			// phpcs:enable Generic.PHP.DeprecatedFunctions.Deprecated
```

2024-11-05 13:41 UTC, vijetaR commented on inc/class-hfe-settings-page.php
> +			// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
Added ruleset to exclude snake case in phpcs.xml.dist file @vrundakansara

2024-11-05 13:44 UTC, vrundakansara requested changes

2024-11-05 13:44 UTC, vrundakansara commented on inc/class-hfe-settings-page.php
> +		if ( $php_version_under_eight && isset( $libxml_disable_entity_loader ) ) {
```suggestion
		if ( $php_version_under_eight && isset( $libxml_disable_entity_loader ) function_exists( 'libxml_disable_entity_loader' ) ) {
```

2024-11-05 13:57 UTC, vrundakansara approved these changes

2024-11-06 05:41 UTC, sushmak02 approved these changes

2024-11-06 05:41 UTC, merged